version: "3"

services:
  redis:
    image: redis:6.2-alpine
    container_name: "wallet-redis"
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --save 20 1 --loglevel ${REDIS_LOG_LEVEL} --requirepass ${REDIS_PASSWORD}
    volumes: 
      - wallet-redis:/data
  database:
    image: mysql:latest
    container_name: "wallet-database"
    restart: "always"
    ports:
      - "127.0.0.1:${MYSQL_PORT}:3306"
    volumes:
      - wallet-db:/var/lib/mysql
      - ./docker/scripts/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wallet-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "wallet-phpmyadmin"
    links:
      - database
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    volumes: 
      - /sessions
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge

volumes:
  wallet-db:
    driver: local
  wallet-redis:
    driver: local